### ISSUE TITLE
Update did:web Universal Resolver to support verificationMethod

### ISSUE THREAD

**Issue by peacekeeper** [uport-project/uport-did-driver#12]
The Universal Resolver did:web driver throws an error if a DID document doesn't contain "publicKey" (which has long been removed from DID Core).

The driver on DockerHub is 6 months old, would it be possible to push an update? https://hub.docker.com/r/uport/uni-resolver-driver-did-uport/

See also https://github.com/decentralized-identity/universal-resolver/issues/168 and https://github.com/w3c-ccg/did-method-web/issues/24.

**Comment by peacekeeper** [comment]
Or should the Universal Resolver use different drivers for did:web and did:ethr than https://hub.docker.com/r/uport/uni-resolver-driver-did-uport/ ?

**Comment by mirceanis** [comment]
I'm not aware of any other implementations.

We've got a bunch of updates lined up to the did:web and did:ethr resolvers that are supposed to bring them much closer to did core spec.
They should be merged in the next few days at which point I'll rebuild the docker image and let you know

**Comment by mirceanis** [comment]
@peacekeeper the @latest docker tag should have this fix along with a number of other fixes.

The `did:ethr` and `did:web` resolvers now return DID resolution results instead of DID documents.
I'm not sure if something special needs to be updated to accommodate this

**Comment by mirceanis** [comment]
@peacekeeper I created a PR in uniresolver with the update. Please take a look: https://github.com/decentralized-identity/universal-resolver/pull/180
