### ISSUE TITLE
Rebuild and push Docker image

### ISSUE THREAD

**Issue by peacekeeper** [uport-project/uport-did-driver#5]
Could you rebuild this Docker image and push it to `uport/uni-resolver-driver-did-uport:latest`?

We'd like to use it with this fix applied: https://github.com/decentralized-identity/web-did-resolver/pull/29

**Comment by OR13** [comment]
You may want to add a Github action to do this in the future: https://github.com/transmute-industries/vc.transmute.world/blob/master/.github/workflows/publish-to-dockerhub.yml

**Comment by mirceanis** [comment]
@peacekeeper yes, coming up.
@OR13 thank you for the suggestion!

**Comment by mirceanis** [comment]
@peacekeeper please see [`uport/uni-resolver-driver-did-uport:1.3.1`](https://hub.docker.com/layers/uport/uni-resolver-driver-did-uport/1.3.1/images/sha256-b7e52e94928acb45cb139f326968f5201a0d08529f1e30c9dd5454f74d9a1559?context=repo)

(I also pushed `latest` but perhaps it's better to use a versioned image)

**Comment by mirceanis** [comment]
I don't know what the protocol is to update the supported DID methods, but I updated the example list with all the ones that are supported by this version.

https://github.com/uport-project/uport-did-driver/blob/7f366f37d22b4c621737d1cfe5cc6b618f7e4444/expressresolver.js#L67

**Comment by peacekeeper** [comment]
@mirceanis thanks for the note, I updated the Universal Resolver configuration accordingly to use the 1.3.1 tag of your driver! See https://github.com/decentralized-identity/universal-resolver/commit/bae0b88b607b53c30e65de3abb8a157a5f20935a

Also thank you for listing some example DIDs.

**Comment by mirceanis** [comment]
@peacekeeper Am I correct to assume this is where you connect the DID methods with a specific container?

https://github.com/decentralized-identity/universal-resolver/blob/bae0b88b607b53c30e65de3abb8a157a5f20935a/config.json#L40

Are the `testIdentifiers` used to list examples on uniresolver.io?

**Comment by peacekeeper** [comment]
@mirceanis sorry for the late response

> Am I correct to assume this is where you connect the DID methods with a specific container?
> 
> https://github.com/decentralized-identity/universal-resolver/blob/bae0b88b607b53c30e65de3abb8a157a5f20935a/config.json#L40

Yes that's right.

> Are the `testIdentifiers` used to list examples on uniresolver.io?

No, right now there's a separate list here https://github.com/decentralized-identity/universal-resolver-frontend/blob/master/src/components/Resolver.jsx#L17. But we should probably change that to use the `testIdentifiers` instead.
