### ISSUE TITLE
Rebuild and push Docker image

### ISSUE THREAD

**Issue by peacekeeper** [uport-project/uport-did-driver#8]
Hello, is the Docker image for the Universal Resolver https://hub.docker.com/r/uport/uni-resolver-driver-did-uport still up-to-date? We're trying to resolve `did:web:data-vault.eu:u:zi4xgcHtYo7fh_KAURaO1beG2v6WN9ImVnQ30CBDEJjLrw` with it and we're getting this error:

```
uni-resolver-driver-did-uport_1  | Error: DID must resolve to a valid https URL containing a JSON document: invalid json response body at https://data-vault.eu/en reason: Unexpected token < in JSON at position 0
uni-resolver-driver-did-uport_1  |     at /opt/uport-did-driver/node_modules/web-did-resolver/lib/resolver.js:81:31
uni-resolver-driver-did-uport_1  |     at step (/opt/uport-did-driver/node_modules/web-did-resolver/lib/resolver.js:32:23)
uni-resolver-driver-did-uport_1  |     at Object.throw (/opt/uport-did-driver/node_modules/web-did-resolver/lib/resolver.js:13:53)
uni-resolver-driver-did-uport_1  |     at rejected (/opt/uport-did-driver/node_modules/web-did-resolver/lib/resolver.js:5:65)
uni-resolver-driver-did-uport_1  |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Maybe you can rebuild and push the image?

**Comment by mirceanis** [comment]
Thanks for flagging this.
The image was a bit behind but I updated it.

It is fixed now in [v1.4.0](https://hub.docker.com/layers/uport/uni-resolver-driver-did-uport/1.4.0/images/sha256-cd8799243a3fef2a71b3662c48645bcd502fe9f417ff517f60378ab837e5cde9?context=explore) which is also [latest](https://hub.docker.com/layers/uport/uni-resolver-driver-did-uport/latest/images/sha256-cd8799243a3fef2a71b3662c48645bcd502fe9f417ff517f60378ab837e5cde9?context=explore)
